import "server-only";

import { randomBytes } from "node:crypto";

import { connectToDatabase } from "@/lib/db/mongoose";
import { StoredUpload } from "@/models";

/**
 * Uploads live in MongoDB, never on disk. Serverless filesystems are ephemeral,
 * so anything written to /public or /tmp disappears on the next deployment.
 */

export const UPLOAD_FOLDERS = ["products", "gallery", "pages", "misc"] as const;
export type UploadFolder = (typeof UPLOAD_FOLDERS)[number];

export const MAX_UPLOAD_BYTES = 8 * 1024 * 1024; // 8MB

export const ALLOWED_MIME_TYPES: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
};

export function isUploadFolder(value: unknown): value is UploadFolder {
  return typeof value === "string" && (UPLOAD_FOLDERS as readonly string[]).includes(value);
}

/**
 * Filenames are generated by us, never taken from the client. This check guards
 * the read route, where the segment is user-controlled.
 */
export function sanitizeFilename(value: string): string | null {
  if (!value) return null;
  if (value.includes("/") || value.includes("\\") || value.includes("..")) return null;
  if (!/^[A-Za-z0-9._-]+$/.test(value)) return null;
  if (value.length > 128) return null;
  return value;
}

export function buildFilename(mimeType: string): string {
  const ext = ALLOWED_MIME_TYPES[mimeType] ?? "bin";
  return `${Date.now()}-${randomBytes(6).toString("hex")}.${ext}`;
}

export function uploadPublicUrl(folder: string, filename: string): string {
  return `/api/uploads/${folder}/${filename}`;
}

/** Parses a stored public URL back into its folder + filename, or null. */
export function parseUploadUrl(
  url: string | null | undefined,
): { folder: UploadFolder; filename: string } | null {
  if (!url || !url.startsWith("/api/uploads/")) return null;
  const parts = url.slice("/api/uploads/".length).split("/");
  if (parts.length !== 2) return null;
  const [folder, rawName] = parts;
  if (!isUploadFolder(folder)) return null;
  const filename = sanitizeFilename(rawName ?? "");
  if (!filename) return null;
  return { folder, filename };
}

export type SaveUploadInput = {
  folder: UploadFolder;
  mimeType: string;
  bytes: Buffer;
  originalName?: string;
};

export async function saveUpload(input: SaveUploadInput) {
  await connectToDatabase();
  const filename = buildFilename(input.mimeType);
  const doc = await StoredUpload.create({
    folder: input.folder,
    filename,
    mimeType: input.mimeType,
    size: input.bytes.byteLength,
    data: input.bytes,
    originalName: input.originalName?.slice(0, 200) ?? "",
  });
  return {
    url: uploadPublicUrl(doc.folder, doc.filename),
    filename: doc.filename,
    folder: doc.folder,
    size: doc.size,
  };
}

/**
 * Idempotent. Deletes only uploads we own (URLs under /api/uploads/), and never
 * touches external URLs or legacy /uploads/ paths.
 */
export async function deleteUploadByUrl(url: string | null | undefined): Promise<boolean> {
  const parsed = parseUploadUrl(url);
  if (!parsed) return false;
  try {
    await connectToDatabase();
    const result = await StoredUpload.deleteOne({
      folder: parsed.folder,
      filename: parsed.filename,
    });
    return result.deletedCount > 0;
  } catch (error) {
    console.error("[usagwp] failed to delete upload", url, error);
    return false;
  }
}

/**
 * Replace helper. Deletes the previous image only when it actually changed, so
 * saving a form without touching the image never destroys the current file.
 */
export async function deleteReplacedUpload(
  previousUrl: string | null | undefined,
  nextUrl: string | null | undefined,
): Promise<void> {
  if (!previousUrl) return;
  if (previousUrl === nextUrl) return;
  await deleteUploadByUrl(previousUrl);
}
